### ISSUE TITLE
nodePort is not 30901 but 30900

### ISSUE THREAD

**Issue by goek-han** [veerendra2/prometheus-k8s-monitoring#1]
nodePort is 30900: https://github.com/veerendra2/prometheus-k8s-monitoring/blob/ce900ae820bfc74ea20b835e2168ed82fedd615a/prometheus-deployment.yml#L17

**Comment by veerendra2** [comment]
Hey geok-han,
Thanks for opening the issue. I think, you are referring the conflicts between [README.md](https://github.com/veerendra2/prometheus-k8s-monitoring) and [prometheus-deployment.yml](https://github.com/veerendra2/prometheus-k8s-monitoring/blob/master/prometheus-deployment.yml#L17) which I mentioned 30901 in README.md and 30900 in prometheus-deployment.yml?

**Comment by veerendra2** [comment]
I have changed in README.md. https://github.com/veerendra2/prometheus-k8s-monitoring/commit/93385d0f7680f28fc78fa9f11b2098057bddfdd9
